# TODO: IMPLEMENT IT
ROW_ACTIVE = 'ACTIVE'
COLUMN_IMAGE_PATH = 'IMAGE PATH'
COLUMN_IMAGE_FILE_NAME = 'IMAGE FILE NAME'
STATUS_PROCESSED = 'PROCESSED'
STATUS_PROCESSING = 'PROCESSING'    
STATUS_COMPLETED = 'COMPLETED'
STATUS_FAILED = 'FAILED'
TAG_SEPARATOR = '_' 
PATH_SEPARATOR = '/'
OUT_FOLDER_PARAMETER = 'out'
DEFAULT_CONFIG_FILE = 'config.json' 
LOG_LEVEL = 'DEBUG'
MAX_TOKENS = 1024